<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Competition;
use App\Models\League;
use App\Models\Season;
use App\Models\Team;
use App\Models\User;
use App\Models\Player;
use App\Models\PlayerGameStat;
use App\Models\PlayerSeasonStat;
use App\Models\GameEvent;
use App\Models\Plan;
use App\Models\Subscription;
use App\Models\Payment;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;
use App\Models\Game;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Roles and Super Admin
        $superAdminRole = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        $superAdmin = User::updateOrCreate(
            ['email' => 'admin@baseball-saas.com'],
            [
                'name' => 'Super Admin',
                'password' => bcrypt('password'),
                'email_verified_at' => now(),
            ]
        );

        $superAdmin->assignRole($superAdminRole);

        $roles = [
            'panel_user',
            'league_owner',
            'team_owner',
            'secretary',
            'coach',
            'player',
            'scorer'
        ];

        foreach ($roles as $role) {
            Role::firstOrCreate(['name' => $role, 'guard_name' => 'web']);
        }

        // 1.5. Plans
        $basicPlan = Plan::firstOrCreate(
            ['slug' => 'basic-academy'],
            [
                'name' => 'Basic Academy',
                'description' => 'Perfect for single academies.',
                'price' => 29.99,
                'currency' => 'USD',
                'duration_days' => 30,
                'max_teams' => 1,
                'is_active' => true,
            ]
        );

        $proPlan = Plan::firstOrCreate(
            ['slug' => 'pro-league'],
            [
                'name' => 'Pro League',
                'description' => 'For leagues and multiple teams.',
                'price' => 99.99,
                'currency' => 'USD',
                'duration_days' => 30,
                'max_teams' => 10,
                'is_active' => true,
            ]
        );

        // 2. SaaS Demo Data (Leagues, Teams, Players, Seasons, Competitions, Games, Stats)
        $leaguesCount = 2;
        $teamsPerLeague = 6;
        $playersPerTeam = 15;
        $categoriesPerLeague = 2;

        $leagues = League::factory()->count($leaguesCount)->create();

        // 2.1 Indepedent Teams (Sin Liga)
        for ($i = 1; $i <= 3; $i++) {
            $teamName = 'Independent Academy ' . $i;
            $team = Team::create([
                'league_id' => null,
                'name' => $teamName,
                'slug' => Str::slug($teamName . '-' . uniqid()),
                'logo' => null,
                'city' => 'Caracas',
            ]);

            // Create Academy Owner for this team
            $teamOwner = User::factory()->create([
                'name' => 'Owner ' . $team->name,
                'email' => 'academy' . $i . '@example.com',
                'password' => Hash::make('password'),
            ]);
            $team->users()->attach($teamOwner);

            // Subscription and Payments
            $subscription = Subscription::create([
                'user_id' => $teamOwner->id,
                'plan_id' => $basicPlan->id,
                'starts_at' => now()->subMonths(3),
                'expires_at' => now()->addDays(15),
                'status' => 'active',
            ]);

            for ($m = 0; $m < 3; $m++) {
                Payment::create([
                    'user_id' => $teamOwner->id,
                    'subscription_id' => $subscription->id,
                    'plan_id' => $basicPlan->id,
                    'payment_method' => 'zelle',
                    'reference_number' => 'REF-' . strtoupper(Str::random(8)),
                    'amount' => $basicPlan->price,
                    'currency' => $basicPlan->currency,
                    'status' => 'approved',
                    'notes' => 'Monthly subscription generated by seeder.',
                    'verified_at' => now()->subMonths(3 - $m),
                    'created_at' => now()->subMonths(3 - $m),
                    'updated_at' => now()->subMonths(3 - $m),
                ]);
            }
            $teamOwner->assignRole('team_owner');

            // Players for this team
            for ($p = 1; $p <= $playersPerTeam; $p++) {
                Player::create([
                    'team_id' => $team->id,
                    'league_id' => null,
                    'name' => 'Indie Player ' . $p,
                    'last_name' => 'Apellido ' . $p,
                    'number' => rand(1, 99),
                    'position' => ['LHP', 'RHP', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF'][rand(0, 9)],
                ]);
            }
        }

        // 2.2 League Teams
        $leagueIndex = 1;
        foreach ($leagues as $league) {
            // League Owner
            $leagueOwner = User::factory()->create([
                'name' => 'League Owner ' . $league->name,
                'email' => 'league' . $leagueIndex . '@example.com',
                'password' => Hash::make('password'),
            ]);
            $league->users()->attach($leagueOwner);
            $leagueOwner->assignRole('league_owner');

            // Subscription and Payments for League Owner
            $leagueSubscription = Subscription::create([
                'user_id' => $leagueOwner->id,
                'plan_id' => $proPlan->id,
                'starts_at' => now()->subMonths(6),
                'expires_at' => now()->addDays(20),
                'status' => 'active',
            ]);

            for ($m = 0; $m < 6; $m++) {
                Payment::create([
                    'user_id' => $leagueOwner->id,
                    'subscription_id' => $leagueSubscription->id,
                    'plan_id' => $proPlan->id,
                    'payment_method' => 'zelle',
                    'reference_number' => 'REF-' . strtoupper(Str::random(8)),
                    'amount' => $proPlan->price,
                    'currency' => $proPlan->currency,
                    'status' => 'approved',
                    'notes' => 'Pro League monthly subscription.',
                    'verified_at' => now()->subMonths(6 - $m),
                    'created_at' => now()->subMonths(6 - $m),
                    'updated_at' => now()->subMonths(6 - $m),
                ]);
            }

            // Teams
            for ($i = 1; $i <= $teamsPerLeague; $i++) {
                $teamName = $league->name . ' Team ' . $i;
                $team = Team::create([
                    'league_id' => $league->id,
                    'name' => $teamName,
                    'slug' => Str::slug($teamName . '-' . uniqid()),
                    'logo' => null,
                ]);

                // Create Academy Owner for this team
                $teamOwner = User::factory()->create([
                    'name' => 'Academy Owner ' . $team->name,
                    'email' => 'team' . $i . '-league' . $leagueIndex . '@example.com',
                    'password' => Hash::make('password'),
                ]);
                $team->users()->attach($teamOwner);
                $teamOwner->assignRole('team_owner');

                // Players for this team
                for ($p = 1; $p <= $playersPerTeam; $p++) {
                    Player::create([
                        'team_id' => $team->id,
                        'league_id' => $league->id,
                        'name' => 'Player ' . $p,
                        'last_name' => $team->name,
                        'number' => rand(1, 99),
                        'position' => ['LHP', 'RHP', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF'][rand(0, 9)],
                    ]);
                }
            }

            // Reference teams for categories
            $teams = $league->teams;

            // Categories
            $categories = Category::factory()->count($categoriesPerLeague)->create([
                'league_id' => $league->id,
            ]);

            // Distribute teams into categories
            $shuffledTeams = $teams->shuffle();
            $chunks = $shuffledTeams->split($categories->count());

            foreach ($categories as $index => $category) {
                $teamsInCat = $chunks->get($index);
                if ($teamsInCat) {
                    $category->teams()->attach($teamsInCat->pluck('id')->toArray(), ['status' => 'approved']);
                }
            }

            // Seasons
            $seasons = Season::factory()->count(2)->sequence(
                ['is_active' => true, 'name' => 'Season 2026'],
                ['is_active' => false, 'name' => 'Season 2025']
            )->create([
                'league_id' => $league->id,
            ]);

            foreach ($seasons as $season) {
                foreach ($categories as $category) {
                    $competition = Competition::factory()->create([
                        'season_id' => $season->id,
                        'category_id' => $category->id,
                        'name' => 'Torneo ' . $category->name,
                    ]);

                    // Roster for Season
                    foreach ($category->teams as $team) {
                        foreach ($team->players as $player) {
                            DB::table('team_player_season')->insertOrIgnore([
                                'team_id' => $team->id,
                                'player_id' => $player->id,
                                'season_id' => $season->id,
                                'number' => $player->number,
                                'position' => $player->position,
                                'created_at' => now(),
                                'updated_at' => now(),
                            ]);
                        }
                    }

                    // Games
                    $teamsInComp = $category->teams;
                    if ($teamsInComp->count() >= 2) {
                        // Create Finished Games
                        $games = Game::factory()->count(10)->create([
                            'league_id' => $league->id,
                            'category_id' => $category->id,
                            'competition_id' => $competition->id,
                            'home_team_id' => $teamsInComp->random()->id,
                            'visitor_team_id' => $teamsInComp->random()->id,
                        ]);

                        foreach ($games as $idx => $game) {
                            if ($game->home_team_id === $game->visitor_team_id) {
                                $game->visitor_team_id = $teamsInComp->where('id', '!=', $game->home_team_id)->random()->id;
                                $game->save();
                            }

                            // Let's make some games upcoming, and others finished
                            if ($idx < 2) {
                                // Upcoming
                                $game->update([
                                    'status' => 'scheduled',
                                    'start_time' => now()->addDays(rand(1, 10)),
                                ]);
                                continue;
                            }

                            $homeScore = rand(1, 15);
                            $visitorScore = rand(1, 15);
                            if ($homeScore === $visitorScore) $homeScore++; // Evitar empates

                            $game->update([
                                'status' => 'finished',
                                'home_score' => $homeScore,
                                'visitor_score' => $visitorScore,
                                'start_time' => now()->subDays(rand(1, 30)),
                            ]);

                            // Stats
                            $homePlayers = Player::where('team_id', $game->home_team_id)->get();
                            $awayPlayers = Player::where('team_id', $game->visitor_team_id)->get();
                            
                            $players = $homePlayers->merge($awayPlayers);
                            
                            // Determinar pitcher ganador y perdedor
                            $winningTeamId = $homeScore > $visitorScore ? $game->home_team_id : $game->visitor_team_id;
                            $losingTeamId = $homeScore > $visitorScore ? $game->visitor_team_id : $game->home_team_id;
                            
                            $losingPitchers = $players->where('team_id', $losingTeamId)->whereIn('position', ['LHP', 'RHP'])->values();
                            $winningPitchers = $players->where('team_id', $winningTeamId)->whereIn('position', ['LHP', 'RHP'])->values();

                            $winnerPitcherId = $winningPitchers->count() > 0 ? $winningPitchers->first()->id : null;
                            $loserPitcherId = $losingPitchers->count() > 0 ? $losingPitchers->first()->id : null;

                            foreach ($players as $player) {
                                $isPitcher = in_array($player->position, ['LHP', 'RHP']);
                                
                                $ab = rand(3, 5);
                                $h = rand(0, 3);
                                $r = rand(0, 2);
                                
                                $isWinnerPitcher = $player->id === $winnerPitcherId;
                                $isLoserPitcher = $player->id === $loserPitcherId;

                                PlayerGameStat::create([
                                    'player_id' => $player->id,
                                    'game_id' => $game->id,
                                    'team_id' => $player->team_id,
                                    'ab' => $isPitcher ? 0 : $ab,
                                    'h' => $isPitcher ? 0 : $h,
                                    'r' => $isPitcher ? 0 : $r,
                                    'rbi' => $isPitcher ? 0 : rand(0, 3),
                                    'hr' => $isPitcher ? 0 : ($h > 0 ? rand(0, 1) : 0),
                                    'doubles' => $isPitcher ? 0 : ($h > 0 ? rand(0, 1) : 0),
                                    'bb' => $isPitcher ? 0 : rand(0, 2),
                                    'so' => $isPitcher ? 0 : rand(0, 2),
                                    'sb' => $isPitcher ? 0 : rand(0, 2),
                                    // Pitching
                                    'ip' => $isPitcher ? rand(1, 9) : 0,
                                    'p_h' => $isPitcher ? rand(2, 6) : 0,
                                    'p_r' => $isPitcher ? rand(0, 5) : 0,
                                    'p_er' => $isPitcher ? rand(0, 4) : 0,
                                    'p_bb' => $isPitcher ? rand(0, 3) : 0,
                                    'p_so' => $isPitcher ? rand(2, 10) : 0,
                                    'w' => $isWinnerPitcher ? 1 : 0,
                                    'l' => $isLoserPitcher ? 1 : 0,
                                ]);
                            }

                            // Generate Random Game Events
                            $inn = rand(1, 4);
                            for ($e=0; $e < $inn; $e++) {
                                GameEvent::create([
                                    'game_id' => $game->id,
                                    'inning' => rand(1, 9),
                                    'is_top_inning' => (rand(0, 1) == 1),
                                    'team_id' => (rand(0, 1) == 1) ? $game->visitor_team_id : $game->home_team_id,
                                    'batter_id' => $players->random()->id,
                                    'pitcher_id' => $players->whereIn('position', ['LHP', 'RHP'])->random()->id ?? null,
                                    'outs_before' => rand(0, 2),
                                    'balls_before' => rand(0, 3),
                                    'strikes_before' => rand(0, 2),
                                    'type' => ['hit', 'out', 'strikeout', 'walk', 'home_run'][rand(0, 4)],
                                    'result' => ['description' => 'Play ball generated.'],
                                    'runs_scored' => rand(0, 2),
                                    'created_by' => $superAdmin->id,
                                ]);
                            }
                        }
                    }
                }
            }
            $leagueIndex++;
        }

        // 3. Generar Player Season Stats consolidando las estadísticas generadas
        $allPlayers = Player::all();
        $allSeasons = Season::all();

        foreach ($allSeasons as $season) {
            foreach ($allPlayers as $player) {
                // Simular que algunos jugadores no jugaron en la temporada para no sobrecargar
                if (rand(1, 10) > 8) continue;

                $isPitcher = in_array($player->position, ['LHP', 'RHP']);
                
                PlayerSeasonStat::create([
                    'player_id' => $player->id,
                    'season_id' => $season->id,
                    'team_id' => $player->team_id,
                    // Batting
                    'g' => rand(10, $season->is_active ? 20 : 40),
                    'ab' => $isPitcher ? 0 : rand(30, 150),
                    'r' => $isPitcher ? 0 : rand(5, 40),
                    'h' => $isPitcher ? 0 : rand(10, 50),
                    'singles' => $isPitcher ? 0 : rand(5, 20),
                    'doubles' => $isPitcher ? 0 : rand(0, 15),
                    'triples' => $isPitcher ? 0 : rand(0, 5),
                    'hr' => $isPitcher ? 0 : rand(0, 10),
                    'rbi' => $isPitcher ? 0 : rand(5, 30),
                    'bb' => $isPitcher ? 0 : rand(5, 25),
                    'so' => $isPitcher ? 0 : rand(10, 40),
                    'sb' => $isPitcher ? 0 : rand(0, 15),
                    'cs' => $isPitcher ? 0 : rand(0, 5),
                    'hbp' => $isPitcher ? 0 : rand(0, 5),
                    'sh' => $isPitcher ? 0 : rand(0, 5),
                    'sacrifice_flies' => $isPitcher ? 0 : rand(0, 5),
                    // Pitching
                    'w' => $isPitcher ? rand(1, 10) : 0,
                    'l' => $isPitcher ? rand(1, 8) : 0,
                    'sv' => $isPitcher ? rand(0, 15) : 0,
                    'ip' => $isPitcher ? (rand(200, 1000) / 10) : 0,
                    'p_h' => $isPitcher ? rand(20, 100) : 0,
                    'p_r' => $isPitcher ? rand(10, 50) : 0,
                    'p_er' => $isPitcher ? rand(8, 45) : 0,
                    'p_bb' => $isPitcher ? rand(10, 40) : 0,
                    'p_so' => $isPitcher ? rand(20, 120) : 0,
                    'p_hr' => $isPitcher ? rand(0, 15) : 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}